language = "phonics_tsalagi"
write_command ="gowelodi"
phonics = {
	a={name="a", length=.4, gain=1, is_letter=0},
	e={name="e", length=.65, gain=1, is_letter=0},
	i={name="i", length=.65, gain=1, is_letter=0},
	o={name="o", length=.65, gain=1, is_letter=0},
	u={name="u", length=.65, gain=1, is_letter=0},	
	v={name="v", length=.65, gain=1, is_letter=0},	
	s={name="s", length=.92, gain=1, is_letter=0},
	ga={name="ga", length=.90, gain=1, is_letter=0},
	ka={name="ka", length=.90, gain=1, is_letter=0},
	ge={name="ge", length=.90, gain=1, is_letter=0},
	gi={name="gi", length=.90, gain=1, is_letter=0},
	go={name="go", length=.90, gain=1, is_letter=0},
	gu={name="gu", length=.90, gain=1, is_letter=0},
	gv={name="gv", length=.90, gain=1, is_letter=0},
	ha={name="ha", length=.90, gain=1, is_letter=0},
	he={name="he", length=.90, gain=1, is_letter=0},
	hi={name="hi", length=.90, gain=1, is_letter=0},
	ho={name="ho", length=.90, gain=1, is_letter=0},
	hu={name="hu", length=.90, gain=1, is_letter=0},
	hv={name="hv", length=.90, gain=1, is_letter=0},
	la={name="la", length=.90, gain=1, is_letter=0},
	le={name="le", length=.90, gain=1, is_letter=0}, 
	li={name="li", length=.90, gain=1, is_letter=0},
	lo={name="lo", length=.90, gain=1, is_letter=0},
	lu={name="lu", length=.90, gain=1, is_letter=0},
	lv={name="lv", length=.90, gain=1, is_letter=0},
	ma={name="ma", length=.90, gain=1, is_letter=0},
	me={name="me", length=.90, gain=1, is_letter=0},
	mi={name="mi", length=.90, gain=1, is_letter=0},
	mo={name="mo", length=.90, gain=1, is_letter=0},
	mu={name="mu", length=.90, gain=1, is_letter=0},
	na={name="na", length=.90, gain=1, is_letter=0},
        hna={name="hna", length=.90, gain=1, is_letter=0},
	nah={name="nah", length=.90, gain=1, is_letter=0},	
	ne={name="ne", length=.90, gain=1, is_letter=0},
	ni={name="ni", length=.90, gain=1, is_letter=0},
	no={name="no", length=.90, gain=1, is_letter=0},
	nu={name="nu", length=.90, gain=1, is_letter=0},
	nv={name="nv", length=.90, gain=1, is_letter=0},
	qua={name="qua", length=.90, gain=1, is_letter=0},
	que={name="que", length=.90, gain=1, is_letter=0},
	qui={name="qui", length=.90, gain=1, is_letter=0}, 
	quo={name="quo", length=.90, gain=1, is_letter=0},
	quu={name="quu", length=.90, gain=1, is_letter=0},
	quv={name="quv", length=.90, gain=1, is_letter=0},
	sa={name="sa", length=.90, gain=1, is_letter=0},
	se={name="se", length=.90, gain=1, is_letter=0},
	si={name="si", length=.90, gain=1, is_letter=0},
	so={name="so", length=.90, gain=1, is_letter=0},
	su={name="su", length=.90, gain=1, is_letter=0},
	sv={name="sv", length=.90, gain=1, is_letter=0},
	da={name="da", length=.90, gain=1, is_letter=0},
	ta={name="ta", length=.90, gain=1, is_letter=0},
	de={name="de", length=.90, gain=1, is_letter=0},
	te={name="te", length=.90, gain=1, is_letter=0},
	di={name="di", length=.90, gain=1, is_letter=0},
	ti={name="ti", length=.90, gain=1, is_letter=0},
	["do"]={name="do", length=.90, gain=1, is_letter=0},
	du={name="du", length=.90, gain=1, is_letter=0},
	dv={name="dv", length=.90, gain=1, is_letter=0},
	dla={name="dla", length=.90, gain=1, is_letter=0},
	tla={name="tla", length=.90, gain=1, is_letter=0},
	tle={name="tle", length=.90, gain=1, is_letter=0},
	tli={name="tli", length=.90, gain=1, is_letter=0},
	tlo={name="tlo", length=.90, gain=1, is_letter=0},
	tlu={name="tlu", length=.90, gain=1, is_letter=0},
	tlv={name="tlv", length=.90, gain=1, is_letter=0},
	tsa={name="tsa", length=.90, gain=1, is_letter=0},
	tse={name="tse", length=.90, gain=1, is_letter=0},
	tsi={name="tsi", length=.90, gain=1, is_letter=0},
	tso={name="tso", length=.90, gain=1, is_letter=0},
	tsu={name="tsu", length=.90, gain=1, is_letter=0},
	tsv={name="tsv", length=.90, gain=1, is_letter=0},
	wa={name="wa", length=.90, gain=1, is_letter=0},
	we={name="we", length=.90, gain=1, is_letter=0},
	wi={name="wi", length=.90, gain=1, is_letter=0},
	wo={name="wo", length=.90, gain=1, is_letter=0},
	wu={name="wu", length=.90, gain=1, is_letter=0},
	wv={name="wv", length=.90, gain=1, is_letter=0},
	ya={name="ya", length=.90, gain=1, is_letter=0},
	ye={name="ye", length=.90, gain=1, is_letter=0},
	yi={name="yi", length=.90, gain=1, is_letter=0},
	yo={name="yo", length=.90, gain=1, is_letter=0},
	yu={name="yu", length=.90, gain=1, is_letter=0},
	yv={name="yv", length=.90, gain=1, is_letter=0},
}
	
two_char_phonics = {
	ga= {name="ga"},
	ka= {name="ka"},
	ge= {name="ge"},
	gi= {name="gi"},
	go= {name="go"},
	gu= {name="gu"},
	gv= {name="gv"},
	ha= {name="ha"},
	he= {name="he"},
	hi= {name="hi"},
	ho= {name="ho"},
	hu= {name="hu"},
	hv= {name="hv"},
	la= {name="la"},
	le= {name="le"},
	li= {name="li"},
	lo= {name="lo"},
	lu= {name="lu"},
	lv= {name="lv"},
	ma= {name="ma"},
	me= {name="me"},
	mi= {name="mi"},
	mo= {name="mo"},
	mu= {name="mu"},
	na= {name="na"},
	ne= {name="ne"},
	ni= {name="ni"},
	no= {name="no"},
	nu= {name="nu"},
	nv= {name="nv"},
	sa= {name="sa"},
	se= {name="se"},
	si= {name="si"},
	so= {name="so"},
	su= {name="su"},
	sv= {name="sv"},
	da= {name="da"},
	ta= {name="ta"},
	de= {name="de"},
	te= {name="te"},
	di= {name="di"},
	ti= {name="ti"},
	["do"]= {name="do"},
	du= {name="du"},
	dv= {name="dv"},
	wa= {name="wa"},
	we= {name="we"},
	wi= {name="wi"},
	wo= {name="wo"},
	wu= {name="wu"},
	wv= {name="wv"},
	ya= {name="ya"},
	ye= {name="ye"},
	yi= {name="yi"},
	yo= {name="yo"},
	yu= {name="yu"},
	yv= {name="yv"},
	--wh= {name="wh"}	
}

three_char_phonics = {
	hna= {name="hna"},
	nah= {name="nah"},
	qua= {name="qua"},
	que= {name="que"},
	qui= {name="qui"},
	qwo= {name="quo"},
	quu= {name="quu"},
	quv= {name="quv"},
	dla= {name="dla"},
	tla= {name="tla"},
	tle= {name="tle"},
	tli= {name="tli"},
	tlo= {name="tlo"},
	tlu= {name="tlu"},
	tlv= {name="tlv"},
	tsa= {name="tsa"},
	tse= {name="tse"},
	tsi= {name="tsi"},
	tso= {name="tso"},
	tsu= {name="tsu"},
	tsv= {name="tsv"},
}

phonics_scarcity = tonumber(minetest.settings:get("phonics_scarcity")) or 350
register_nodes(phonics, language, write_command)
register_ores(phonics, language,phonics_scarcity)

local dpath = minetest.get_modpath("phonics_tsalagi") .. "/"
dofile(dpath .. "crafting.lua")
print("phonics_tsalagi Mod Loaded!")
 	--minetest.env:punch_node(pos) 
 	--minetest.env:dig_node(pos) 
 	--http://minetest.net/forum/viewtopic.php?id=2602
 	--https://c9.io/lkjoel/minetest-modder/workspace/parseme.txt
